spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TrumpetPress?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: TrumpetPress
    password: aFmfpjNrzniGRGzP
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: debug