spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TrumpetPress?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Li19991123
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: info